automatic focusing of the search bar when visiting the /search page
RiadhAdrani/slick-portfolio-svelte pull request #20
Opened 2024-01-24 13:18 UTC by M2K3K5

2024-01-24 13:40 UTC, RiadhAdrani commented
The funny part is that I implemented it in my personal website and forgot to apply it in the template 🤷‍♂️

2024-01-24 13:51 UTC, M2K3K5 commented
hhahah lol, then take a look at what else you've missed :D
I've been using your template for a few days now and I think it's just great. I think I'll add a few things too

2024-01-25 21:46 UTC, M2K3K5 commented
Hey, I just visited your website on my cell phone and noticed that the search bar is focused on every page. Because of the cell phone, the cell phone keyboard opens every time I visit the site. Would you like to double check my pull request and apply my idea to focus the search bar only on the /search path (if the user really wants to search something)

2024-01-26 06:30 UTC, RiadhAdrani commented
Hello,
I will be reviewing your prs soon, (mostly tomorrow), sorry for the delayed response !

2024-01-26 13:51 UTC, RiadhAdrani requested changes

2024-01-26 13:51 UTC, RiadhAdrani commented on src/lib/components/SearchPage.svelte
> +			if (path.startsWith('/search')) {
Nice, but you didn't take into consideration the base, import these at the top 

```ts
import { page } from '$app/stores';
import { base } from '$app/paths';
```

and replace this line with :
```ts
if ($page.url.pathname.startsWith(`${base}/search`)) {
```

and we should be good to go !

2024-01-26 17:42 UTC, RiadhAdrani approved these changes
LGTM

2024-01-26 17:42 UTC, merged